### ISSUE TITLE
Fix "victory donuts"

### ISSUE THREAD

**Issue by omc8db** [MST-MRDT/AutonomyBoard-Software#17]
Rover spins in place after reaching waypoint instead of stopping.

**Comment by omc8db** [comment]
Might be related to failing to return to 'idle' state after reaching waypoint

**Comment by Amp21** [comment]
In AutonomyTest.py there was a missing underscore on line #122 

            if reached_goal:
                state = 'waypoint reached' #missing "_" 
should be:

 if reached_goal:
                state = 'waypoint_reached'
change and it looks like it should work fine
