### ISSUE TITLE
Implement Crosstrack Correction

### ISSUE THREAD

**Issue by omc8db** [MST-MRDT/AutonomyBoard-Software#8]
When approaching a waypoint, steer around it a bit so that when you pass through you're already pointing toward the next one.

**Comment by omc8db** [comment]
Resources:

http://gis.stackexchange.com/questions/121117/cross-track-distance-to-great-cicle-line-and-rhumb-line
http://geo.javawa.nl/coordcalc/index_en.html - Look at calculation number 2

We're looking to calculate the distance and heading to the line between two waypoints

**Comment by kohariker** [comment]
Here is an article that basically explains exactly how to find our "D" value on original course (even gives a javascript version of the algorithm). Now we just need to decide how far we want to correct.
http://www.movable-type.co.uk/scripts/latlong.html

I have not read their code, just the cross track logic.
